
name: test Project

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/chechout@v3
      - name: install NodeJS
        uses: action/setup-node@v3
        with:
          node-version: 18
          
      - name: install dependencies 
        run: npm cli
      - name: run test
        run: npm test
        
             
          

